language: php

php:
  - 7.0

branches:
  only:
    - master
    - dev

before_script:
  - composer install --no-interaction --prefer-source

script:
   - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)