#!/usr/bin/env php
<?php
declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

use Raptor\TestUtils\Command\GenerateIDETestContainersCommand;
use Raptor\TestUtils\DataLoader\DataLoaderFactory;
use Raptor\TestUtils\DataLoader\DirectoryDataLoaderFactory;
use Raptor\TestUtils\Generator\TestDataContainerGenerator;
use Symfony\Component\Console\Application;

$application = new Application();
$dataLoaderFactory = new DataLoaderFactory();
$directoryDataLoaderFactory = new DirectoryDataLoaderFactory($dataLoaderFactory);
$directoryDataLoader = $directoryDataLoaderFactory->createTestContainerGeneratorDataLoader();
$generator = new TestDataContainerGenerator($directoryDataLoader);
$filePath = dirname(__DIR__, 3);
$command = new GenerateIDETestContainersCommand($generator, $filePath);
$application->add($command);
$application->setDefaultCommand($command->getName(), true);

/** @noinspection PhpUnhandledExceptionInspection __approved__ no need to handle errors */
$application->run();